# Generated by Django 4.0.4 on 2022-06-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_attendees_alter_event_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClubUser',
        ),
    ]
